export type OperationType =
  | 'SET_THEME'
  | 'START_SESSION'
  | 'GET_STATUS'
  | 'CREATE_OR_ADD_SEED'
  | 'REMOVE_SEED'
  | 'ENTER_PIN_EXTERNAL'
  | 'ENTER_PIN_INTERNAL'
  | 'SIGN_TRANSACTION'
  | 'SIGN_DATA'
  | 'READY';
